DROP  TABLE IF EXISTS PEDIDO;
DROP SEQUENCE IF EXISTS pedido_seq;

CREATE SEQUENCE pedido_seq;

CREATE TABLE PEDIDO (
  ID number(10) PRIMARY KEY,
  FORNECEDOR varchar(100),
  CPF_DO_CLIENTE  number(11),
  DATA  date,
  QUANTIDADE_GALAO_DE_AGUA   number(3),
  QUANTIDADE_SACO_DE_GELO   number(3),
  VALOR   number(10),
  QUANTIDADE_SACO_DE_CARVAO  number(3),
  QUANTIDADE_ACENDEDOR  number(3)
);
